#!/bin/sh

set -e

ARCH=`dpkg-architecture -qDEB_BUILD_ARCH`
V=1.6

PKGS="ros-industrial-libpcl-common ros-industrial-libpcl-features ros-industrial-libpcl-filters"
PKGS="${PKGS} ros-industrial-libpcl-geometry ros-industrial-libpcl-io"
PKGS="${PKGS} ros-industrial-libpcl-io-ply ros-industrial-libpcl-kdtree"
PKGS="${PKGS} ros-industrial-libpcl-keypoints ros-industrial-libpcl-octree"
PKGS="${PKGS} ros-industrial-libpcl-registration ros-industrial-libpcl-sample-consensus"
PKGS="${PKGS} ros-industrial-libpcl-search ros-industrial-libpcl-segmentation"
PKGS="${PKGS} ros-industrial-libpcl-surface ros-industrial-libpcl-tracking"
PKGS="${PKGS} ros-industrial-libpcl-visualization"

for pkg in ${PKGS}; do
    f=`echo ${pkg} | sed 's|-|_|g'`
    pkgkde-gensymbols -p${pkg}${V} -v${V} -Osymbols-${pkg}.${ARCH} \
        -edebian/${pkg}${V}/opt/ros_industrial/pcl-1.9/lib/*/${f}.so.${V}
    pkgkde-symbolshelper create -o debian/${pkg}${V}.symbols -v ${V} \
	symbols-${pkg}.${ARCH}
done
